apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: permissao-imagens
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: permissao-sessao
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aplicacao-sistema-statefulset
spec:
  serviceName: aplicacao-sistema-statefulset
  selector:
    matchLabels:
      name: aplicacao-sistema-pod-statefulset
  template:
    metadata:
      labels:
        name: aplicacao-sistema-pod-statefulset
    spec:
      containers:
      - name: container-sistema-statefulset
        image: renancso/noticia-sistema-alura:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
        lifecycle:
          postStart:
            exec:
              command: ["sh", "enviarMensagens.sh"]
        volumeMounts:
          - mountPath: /var/www/html/uploads
            name: imagens
          - mountPath: /tmp
            name: sessoes
      volumes:
        - name: imagens
          persistentVolumeClaim:
            claimName: permissao-imagens
        - name: sessoes
          persistentVolumeClaim:
            claimName: permissao-sessao
---

apiVersion: v1
kind: Service
metadata:
  name: servico-sistema-noticia-statefulset
spec:
  type: LoadBalancer
  selector:
    name: aplicacao-sistema-pod-statefulset
  ports:
    - name: http
      port: 80
      nodePort: 30047