apiVersion: v1
kind: Service
metadata:
  name: servico-sistema-noticia-statefulset
spec:
  type: LoadBalancer
  selector:
    name: aplicacao-sistema-pod-statefulset
  ports:
    - name: http
      port: 80
      nodePort: 30047
