apiVersion: v1
kind: Pod
metadata:
  name: aplicacao-noticia
  labels:
    name: aplicacao-noticia
spec:
  containers:
  - name: container-aplicacao
    image: jnlucas/image-phpmysql:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
