apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-noticia-deployment
spec:
  selector:
    matchLabels:
      app: aplicacao-noticia-pod
  template:
    metadata:
      labels:
        app: aplicacao-noticia-pod
    spec:
      containers:
      - name: container-aplicacao
        image: jnlucas/image-phpmysql:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
