apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-sistema-deployment
spec:
  selector:
    matchLabels:
      name: aplicacao-sistema-pod
  template:
    metadata:
      labels:
        name: aplicacao-sistema-pod
    spec:
      containers:
      - name: container-sistema
        image: renancso/noticia-sistema-alura:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
