apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-noticia-deployment
spec:
  selector:
    matchLabels:
      name: aplicacao-noticia-pod
  template:
    metadata:
      labels:
        name: aplicacao-noticia-pod
    spec:
      containers:
      - name: container-aplicacao
        image: renancso/noticia-alura:v4
        resources:
          requests:
            cpu: 400m 
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
